pod 'AFPopupView', '~> 1.0'
pod 'DNSSwipeableTableCell', '~> 0.0.1'
pod 'UIView+draggable', '~> 0.2'
pod 'WEPopover', '~> 1.0.0'
pod 'PopoverView', '~> 0.0.1'
pod 'LPPopupListView', '~> 1.0.2'
pod 'JMOTableViewDescription', '~> 0.1'
pod 'PZSideMenuViewController', '~> 1.1.0'